server {
    listen 80;
    server_name localhost;

    # 1. Phục vụ các file tĩnh của giao diện React (HTML, JS, CSS)
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # 2. Điều hướng (Proxy) toàn bộ các request bắt đầu bằng /api sang cho Backend container
    location /api/ {
        proxy_pass http://backend-api:8081/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}