server {
    listen 80;
    # Cấu hình nhận diện tên miền của bạn ở đây
    server_name thanhinterview.xyz www.thanhinterview.xyz;

    # Cấu hình cho Frontend ReactJS
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Cấu hình đẩy request về Java Spring Boot Backend
    location /api/ {
        # Bạn nhớ kiểm tra xem tên "backend-api" này có khớp 100% với tên service backend trong file docker-compose.yml không nhé
        proxy_pass http://backend-api:8081/; 
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_http_version 1.1;
        proxy_set_header Connection "";
    }
}